language: cpp
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libelf-dev libxml2-dev libxslt1-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
compiler:
  - clang
  - gcc
before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: cmake . && make

