language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libelf-dev libxml2-dev libxslt1-dev llvm-3.4-dev
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2-Linux-i386.sh
  - chmod a+x cmake-2.8.12.2-Linux-i386.sh
  - sudo ./cmake-2.8.12.2-Linux-i386.sh --skip-license --prefix=/usr/local
compiler:
  - clang
script: /usr/local/bin/cmake . && make
